budget_guidelines = [
    "The 50/30/20 Rule: Allocate 50% of your income to needs, 30% to wants, and 20% to savings and debt repayment.",
    "Pay Yourself First: Automatically transfer a portion of your paycheck to savings before paying bills.",
    "Emergency Fund: Aim to save 3-6 months' worth of living expenses in a separate, easily accessible account.",
    "Zero-Based Budgeting: Assign every dollar a job so your income minus expenses equals zero.",
    "Needs vs. Wants: Clearly distinguish between essential expenses (housing, food) and discretionary spending.",
    "Debt Snowball Method: Pay off debts from smallest balance to largest to build momentum.",
    "Debt Avalanche Method: Pay off debts with the highest interest rates first to save money on interest.",
    "The 24-Hour Rule: Wait 24 hours before making any non-essential purchase over a certain amount.",
    "Sinking Funds: Save small amounts monthly for large, expected annual expenses like insurance or holidays.",
    "Track Every Expense: Use an app or spreadsheet to record every purchase to identify spending leaks.",
    "Review Subscriptions: Regularly audit and cancel unused or unnecessary monthly subscriptions.",
    "Limit Eating Out: Cook at home more often and meal prep to save significantly on food costs.",
    "Use Cash for Discretionary Spending: Using physical cash can help limit overspending on non-essentials.",
    "Automate Bills: Set up automatic payments to avoid late fees and tracking hassles.",
    "Invest Early: Start investing for retirement as early as possible to take advantage of compound interest.",
    "Match Employer Contributions: Always contribute enough to your 401(k) to get the full employer match.",
    "Audit Your Grocery Bill: Buy generic brands and shop with a list to reduce grocery spending.",
    "No-Spend Days: Challenge yourself to have specific days where you spend zero money.",
    "Negotiate Bills: Call service providers (internet, insurance) annually to negotiate lower rates.",
    "Avoid Lifestyle Creep: As your income increases, keep your living expenses relatively stable.",
    "Set SMART Financial Goals: Make goals Specific, Measurable, Achievable, Relevant, and Time-bound.",
    "Maintain a Good Credit Score: Pay bills on time and keep credit utilization low to access better rates.",
    "Refinance High-Interest Debt: Look for opportunities to refinance loans to lower interest rates.",
    "Use Cashback Apps: Earn small amounts back on necessary purchases using cashback rewards programs.",
    "Buy Used: Purchase furniture, clothes, or cars second-hand to save on depreciation.",
    "Review Insurance Policies: Ensure you aren't over-insured or under-insured annually.",
    "Energy Efficiency: Save on utility bills by using energy-efficient appliances and habits.",
    "Avoid Impulse Buying: Unsubscribe from marketing emails to reduce temptation.",
    "Calculate Hourly Cost: Before buying, calculate how many hours of work the item costs.",
    "Save Windfalls: Put bonuses, tax refunds, or unexpected money directly into savings or debt.",
    "Budget for Fun: Include a specific line item for entertainment so you don't feel deprived.",
    "Check Bank Statements: Review weekly to spot errors or fraud immediately.",
    "Use the Envelope System: Allocate cash into envelopes for different categories; when it's gone, it's gone.",
    "Separate Savings Accounts: Use different accounts for different goals (travel, house, car).",
    "Understanding Net Worth: Track assets minus liabilities to see your overall financial progress.",
    "Opportunity Cost: Consider what you are giving up by making a specific financial choice.",
    "Inflation Protection: Invest in assets that historically outpace inflation over the long term.",
    "Frugal Hobbies: Find low-cost or free activities for entertainment.",
    "DIY When Possible: Learn to do basic repairs or tasks yourself instead of hiring out.",
    "Comparison Shopping: Always compare prices across multiple retailers before big purchases."
]
